# Generated by Django 5.1.6 on 2025-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_userprofile_email_userprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
