# Generated by Django 5.1.6 on 2025-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_userprofile_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='couvertur_image'),
        ),
    ]
